// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TsundokuTraducoes.Auth.Api.Data.Context;

#nullable disable

namespace TsundokuTraducoes.Auth.Api.Migrations
{
    [DbContext(typeof(UsuarioContext))]
    [Migration("20260125172402_Adicao_RBAC_ABAC")]
    partial class Adicao_RBAC_ABAC
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "leitor",
                            NormalizedName = "LEITOR"
                        },
                        new
                        {
                            Id = 3,
                            Name = "tradutor",
                            NormalizedName = "TRADUTOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TsundokuTraducoes.Auth.Api.Entities.ClaimDinamica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ExpiraEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Tipo")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Valor")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Tipo", "Valor")
                        .IsUnique();

                    b.ToTable("ClaimsDinamicas");
                });

            modelBuilder.Entity("TsundokuTraducoes.Auth.Api.Entities.CustomIdentityUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<Guid>("TsunId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "804ef45c-db06-4dd6-8a81-451fd10c2dd1",
                            Email = "tsundokutraducoes@gmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "TSUNDOKUTRADUCOES@GMAIL.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEPV2efEDVfxEY9RE+0OU8CKEjqeRf1vNEDEZV7D8g9aofAPlFQaHY12LMIdSlA9NFA==",
                            PhoneNumberConfirmed = false,
                            RefreshTokenExpiryTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SecurityStamp = "635e141a-4563-4936-a743-bd877794624d",
                            TsunId = new Guid("00000000-0000-0000-0000-000000000000"),
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("TsundokuTraducoes.Auth.Api.Entities.Permissao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Recurso")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Permissoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Acao = "Visualizar",
                            CriadoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3500),
                            Descricao = "Permite visualizar obras",
                            Nome = "VisualizarObras",
                            Recurso = "Obras"
                        },
                        new
                        {
                            Id = 2,
                            Acao = "Criar",
                            CriadoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3500),
                            Descricao = "Permite criar obras",
                            Nome = "CriarObras",
                            Recurso = "Obras"
                        },
                        new
                        {
                            Id = 3,
                            Acao = "Editar",
                            CriadoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3500),
                            Descricao = "Permite editar obras",
                            Nome = "EditarObras",
                            Recurso = "Obras"
                        },
                        new
                        {
                            Id = 4,
                            Acao = "Deletar",
                            CriadoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3510),
                            Descricao = "Permite deletar obras",
                            Nome = "DeletarObras",
                            Recurso = "Obras"
                        },
                        new
                        {
                            Id = 5,
                            Acao = "Visualizar",
                            CriadoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3510),
                            Descricao = "Permite visualizar capítulos",
                            Nome = "VisualizarCapitulos",
                            Recurso = "Capitulos"
                        },
                        new
                        {
                            Id = 6,
                            Acao = "Criar",
                            CriadoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3510),
                            Descricao = "Permite criar capítulos",
                            Nome = "CriarCapitulos",
                            Recurso = "Capitulos"
                        },
                        new
                        {
                            Id = 7,
                            Acao = "Editar",
                            CriadoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3510),
                            Descricao = "Permite editar capítulos",
                            Nome = "EditarCapitulos",
                            Recurso = "Capitulos"
                        },
                        new
                        {
                            Id = 8,
                            Acao = "Deletar",
                            CriadoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3510),
                            Descricao = "Permite deletar capítulos",
                            Nome = "DeletarCapitulos",
                            Recurso = "Capitulos"
                        },
                        new
                        {
                            Id = 9,
                            Acao = "Gerenciar",
                            CriadoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3510),
                            Descricao = "Permite gerenciar usuários",
                            Nome = "GerenciarUsuarios",
                            Recurso = "Usuarios"
                        });
                });

            modelBuilder.Entity("TsundokuTraducoes.Auth.Api.Entities.RolePermissao", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissaoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AtribuidoEm")
                        .HasColumnType("datetime(6)");

                    b.HasKey("RoleId", "PermissaoId");

                    b.HasIndex("PermissaoId");

                    b.ToTable("RolePermissoes");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissaoId = 1,
                            AtribuidoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3540)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissaoId = 2,
                            AtribuidoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3540)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissaoId = 3,
                            AtribuidoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3540)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissaoId = 4,
                            AtribuidoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3540)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissaoId = 5,
                            AtribuidoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3540)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissaoId = 6,
                            AtribuidoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3540)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissaoId = 7,
                            AtribuidoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3540)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissaoId = 8,
                            AtribuidoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3540)
                        },
                        new
                        {
                            RoleId = 1,
                            PermissaoId = 9,
                            AtribuidoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3540)
                        },
                        new
                        {
                            RoleId = 3,
                            PermissaoId = 1,
                            AtribuidoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3540)
                        },
                        new
                        {
                            RoleId = 3,
                            PermissaoId = 2,
                            AtribuidoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3540)
                        },
                        new
                        {
                            RoleId = 3,
                            PermissaoId = 3,
                            AtribuidoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3550)
                        },
                        new
                        {
                            RoleId = 3,
                            PermissaoId = 5,
                            AtribuidoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3550)
                        },
                        new
                        {
                            RoleId = 3,
                            PermissaoId = 6,
                            AtribuidoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3550)
                        },
                        new
                        {
                            RoleId = 3,
                            PermissaoId = 7,
                            AtribuidoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3550)
                        },
                        new
                        {
                            RoleId = 2,
                            PermissaoId = 1,
                            AtribuidoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3550)
                        },
                        new
                        {
                            RoleId = 2,
                            PermissaoId = 5,
                            AtribuidoEm = new DateTime(2026, 1, 25, 17, 24, 2, 386, DateTimeKind.Utc).AddTicks(3550)
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("TsundokuTraducoes.Auth.Api.Entities.CustomIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("TsundokuTraducoes.Auth.Api.Entities.CustomIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TsundokuTraducoes.Auth.Api.Entities.CustomIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("TsundokuTraducoes.Auth.Api.Entities.CustomIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TsundokuTraducoes.Auth.Api.Entities.ClaimDinamica", b =>
                {
                    b.HasOne("TsundokuTraducoes.Auth.Api.Entities.CustomIdentityUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TsundokuTraducoes.Auth.Api.Entities.RolePermissao", b =>
                {
                    b.HasOne("TsundokuTraducoes.Auth.Api.Entities.Permissao", "Permissao")
                        .WithMany("RolePermissoes")
                        .HasForeignKey("PermissaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permissao");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TsundokuTraducoes.Auth.Api.Entities.Permissao", b =>
                {
                    b.Navigation("RolePermissoes");
                });
#pragma warning restore 612, 618
        }
    }
}
